import { Heebo } from "next/font/google";
import "./globals.css";
import Header from "./(Header)/Header";
import Footer from "./(Footer)/Footer";
import { ClerkProvider } from "@clerk/nextjs";

const heebo = Heebo({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={heebo.className}>
        <ClerkProvider>
          <Header />
          {children}
          <Footer />
        </ClerkProvider>
      </body>
    </html>
  );
}
